# ===============================
# Application
# ===============================
spring.application.name=e-commarce

# ===============================
# Server Configuration
# ===============================
server.port=${PORT:8080}
server.servlet.context-path=/api

# ===============================
# JWT Configuration
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===============================
# Database Configuration
# ===============================

# Render will provide DATABASE_URL
# Local will fallback to your local PostgreSQL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/college-project}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:vak123}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Logging (Optional but helpful)
# ===============================
logging.level.org.springframework.security=DEBUG
